### ISSUE TITLE
MD5 Check Should Happen during JSON 2 INI file conversion

### ISSUE THREAD

**Issue by niall-byrne** [ICGC-TCGA-PanCancer/s3-transfer-operations#11]
Based on a conversation I had with Linda, I'd like to suggest a revision to the SOP.

We should be doing an additional MD5 sum check on the XML data, prior to scheduling a workflow.  There is alot of costly overhead associated with moving an ini file to a worker and launching it.
If we catch an MD5 sum difference when we do the JSON 2 INI conversion, we can avoid scheduling jobs we know will fail.

My solution to this, would be to modify the JSON2INI script to do the MD5 check ahead of time, and move any JSON with bad MD5 sums directly to the failed folder- with a commit message that says "BAD MD5 SUM" so that the operator doesn't have to investigate what went wrong.

**Comment by junjun-zhang** [comment]
SOP updated, diff is here: https://github.com/ICGC-TCGA-PanCancer/s3-transfer-operations/commit/8a7472bd63f16165eec7bba87c5c8b7111e8c220

**Comment by niall-byrne** [comment]
I have made changes to accommodate this here:
https://github.com/ICGC-TCGA-PanCancer/s3-transfer-operations/blob/master/scripts/cluster2.cron#L36-L54

This has been rolled out to Cluster-2, I would advise we do the same in Cluster-1.
