### ISSUE TITLE
How to handle the fact that GNOS metadata retrieved by http client contains dynamic content

### ISSUE THREAD

**Issue by junjun-zhang** [ICGC-TCGA-PanCancer/s3-transfer-operations#2]
The issue:
- files to be transferred to S3 need to have file name, md5sum, size populated in pre-generated upload manifest JSON file
- gnos metadata XML retrieved from GNOS server contains a small portion of dynamic content: a timestamp and a query ID
- pre-generated md5sum and file size will not match the one when the workflow retrieve the XML at runtime

Here is an example of the dynamic portion of the XML:

```
<ResultSet date="2015-07-16 16:21:49" id="37692368">
```

Proposal (very simple):
- stripe out the dynamic portion, producing something as below:

```
<ResultSet>
```

Action items:
- striping out dynamic portion when pre-generating upload JSON (for @lindaxiang)
- striping out dynamic portion in workflow after retrieving it from GNOS (for @niall-byrne)

**Comment by niall-byrne** [comment]
This is complete in the workflow portion.

**Comment by junjun-zhang** [comment]
This has already been addressed.

**Comment by niall-byrne** [comment]
I'd like to reopen this to discuss what happened with the changes on the GNOS side (when Annai changed some fields in the data), and get Brian's input before we consider this a resolved problem.  This can potentially cause a ton of extra work for the operator.

**Comment by niall-byrne** [comment]
I believe this is handled correctly by the changes we made to the SOP and JSON2INI script in:
https://github.com/ICGC-TCGA-PanCancer/s3-transfer-operations/issues/11
