### ISSUE TITLE
Possible Git collisions can make a workflow fail

### ISSUE THREAD

**Issue by cphl** [ICGC-TCGA-PanCancer/s3-transfer-operations#5]
Not completely sure the full extent of the problem, but this has been observed only on some rare occasions when the batch size has been 4 (a relatively recent increase) and near-misses have not been looked for when a workflow did not fail.
### A worker will not be able to do a git operation if another worker is performing one simultaneously

This has been observed when 4 workers were launched at the same time and tried to do the git mv to downloading-jobs/ folder. One succeeded on the first try. Two of them had to retry (different numbers of times) before success. The remaining worker could not do it for 6 tries and thus the workflow failed. Timestamps for all workers and all tries were the same, within the same minute. Retries have been observed to happen in rapid succession (under a few seconds between start times).
### Current intervention: Reduced batch-size to 1

This means that workers will be provisioned one at a time (if there are jobs in the queue).

Testing with batch size 3, collisions were still observed (see log file below) but the staggering of retries allowed all of them to go through. However it's possible that some batch could collide enough and fail out.
##### Possible problems with the current intervention:
- If the number of running instances is a significant number below the maximum in a running fleet, a batch size of 1 could mean more time spent getting back to a full-sized fleet. This could happen for example, if the queue is empty (out of jobs in queued-jobs/ or intentional draining of queue for testing or troubleshooting), if many workers finishing simultaneously (the instances are terminated and that same number need to be provisioned), or the fleet size is increased significantly over the previous size (max_running_containers parameter). It takes about 10 minutes to configure a worker. Everything except the git operations can happen simultaneously and independently.
- Workers could still collide during other steps if they happen to coincide. It's much less likely, but we'd still be relying on chance for it to not happen.
### Ideas
- Add more retries
- Add a randomized wait time
- Some combination of the above
- ???
### Log of problem event

This git operation succeeded after a retry (automated by the worker). It was one worker out of 3 started simultaneously. Another worker had similar messages when it had to retry 3 (or more) times. All three had the same timestamp of logfile.

```
-rw-r--r-- 1 ubuntu ubuntu 1227 Aug 17 20:44 s28_git_manage_queued-jobs_downloading-jobs_3.o844241162
-rw-r--r-- 1 ubuntu ubuntu 1264 Aug 17 20:44 s28_git_manage_queued-jobs_downloading-jobs_3.e844241162
-rw-r--r-- 1 ubuntu ubuntu  617 Aug 17 20:44 s28_git_manage_queued-jobs_downloading-jobs_3.stdout
-rw-r--r-- 1 ubuntu ubuntu  123 Aug 17 20:44 s28_git_manage_queued-jobs_downloading-jobs_3.stderr
-rw-r--r-- 1 ubuntu ubuntu  123 Aug 17 20:44 s28_git_manage_queued-jobs_downloading-jobs_3.o844243305
-rw-r--r-- 1 ubuntu ubuntu  783 Aug 17 20:44 s28_git_manage_queued-jobs_downloading-jobs_3.e844243305
drwxrwxrwx 9 ubuntu ubuntu    0 Aug 17 20:44 ..
-rw-r--r-- 1 ubuntu ubuntu    0 Aug 17 20:44 s28_GNOS_download_4.stdout
-rw-r--r-- 1 ubuntu ubuntu    0 Aug 17 20:44 s28_GNOS_download_4.stderr
drwxr-xr-x 2 ubuntu ubuntu    0 Aug 17 20:44 .
[WORKER] ubuntu@i-ade4927f:/datastore/oozie-380fadbf-87a4-46b3-8ddb-6df03b55ed12/generated-scripts$ cat s28_git_manage_queued-jobs_downloading-jobs_3.o844241162 
Already on 'master'
From github.com:ICGC-TCGA-PanCancer/s3-transfer-operations
   792d09f..dd509e6  master     -> origin/master
To git@github.com:ICGC-TCGA-PanCancer/s3-transfer-operations.git
 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'git@github.com:ICGC-TCGA-PanCancer/s3-transfer-operations.git'
To prevent you from losing history, non-fast-forward updates were rejected
Merge the remote changes (e.g. 'git pull') before pushing again.  See the
'Note about fast-forwards' section of 'git push --help' for details.
Already on 'master'
From github.com:ICGC-TCGA-PanCancer/s3-transfer-operations
   792d09f..dd509e6  master     -> origin/master
To git@github.com:ICGC-TCGA-PanCancer/s3-transfer-operations.git
 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'git@github.com:ICGC-TCGA-PanCancer/s3-transfer-operations.git'
To prevent you from losing history, non-fast-forward updates were rejected
Merge the remote changes (e.g. 'git pull') before pushing again.  See the
'Note about fast-forwards' section of 'git push --help' for details.
The method 'do_run' exited abnormally so the Runner will terminate here!
Return value was: 1
[WORKER] ubuntu@i-ade4927f:/datastore/oozie-380fadbf-87a4-46b3-8ddb-6df03b55ed12/generated-scripts$ cat s28_git_manage_queued-jobs_downloading-jobs_3.e844241162
Command run: 
bash -lc /datastore/oozie-380fadbf-87a4-46b3-8ddb-6df03b55ed12/generated-scripts/s28_git_manage_queued-jobs_downloading-jobs_3.sh 
HEAD is now at 792d09f uploading-jobs: 7c7bbff3-b454-4523-8fa4-e17d0fdcd481.BOCA-UK.CGP_donor_1691205.CGP_specimen_1770672.WGS-BWA-Tumor.json
Fetching origin
[master 01b419c] downloading-jobs: 96e252b8-911a-44c7-abc6-b924845e0be6.BOCA-UK.CGP_donor_1437417.CGP_specimen_1491214.WGS-BWA-Tumor.json
 1 file changed, 0 insertions(+), 0 deletions(-)
 rename s3-transfer-jobs/{queued-jobs => downloading-jobs}/96e252b8-911a-44c7-abc6-b924845e0be6.BOCA-UK.CGP_donor_1437417.CGP_specimen_1491214.WGS-BWA-Tumor.json (100%)
[SeqWare Pipeline] ERROR [2015/08/17 20:44:03] | The exit value was 1
Command exit code: 1
HEAD is now at 792d09f uploading-jobs: 7c7bbff3-b454-4523-8fa4-e17d0fdcd481.BOCA-UK.CGP_donor_1691205.CGP_specimen_1770672.WGS-BWA-Tumor.json
Fetching origin
[master 01b419c] downloading-jobs: 96e252b8-911a-44c7-abc6-b924845e0be6.BOCA-UK.CGP_donor_1437417.CGP_specimen_1491214.WGS-BWA-Tumor.json
 1 file changed, 0 insertions(+), 0 deletions(-)
 rename s3-transfer-jobs/{queued-jobs => downloading-jobs}/96e252b8-911a-44c7-abc6-b924845e0be6.BOCA-UK.CGP_donor_1437417.CGP_specimen_1491214.WGS-BWA-Tumor.json (100%)
[WORKER] ubuntu@i-ade4927f:/datastore/oozie-380fadbf-87a4-46b3-8ddb-6df03b55ed12/generated-scripts$ cat s28_git_manage_queued-jobs_downloading-jobs_3.stdout
Your branch and 'origin/master' have diverged,
and have 1 and 1 different commit each, respectively.
HEAD is now at dd509e6 downloading-jobs: 9a442aa9-3cf4-405a-a7dd-dba6a0d92704.BOCA-UK.CGP_donor_1691214.CGP_specimen_1770699.WGS-BWA-Tumor.json
Fetching origin
[master 221b2ab] downloading-jobs: 96e252b8-911a-44c7-abc6-b924845e0be6.BOCA-UK.CGP_donor_1437417.CGP_specimen_1491214.WGS-BWA-Tumor.json
 1 file changed, 0 insertions(+), 0 deletions(-)
 rename s3-transfer-jobs/{queued-jobs => downloading-jobs}/96e252b8-911a-44c7-abc6-b924845e0be6.BOCA-UK.CGP_donor_1437417.CGP_specimen_1491214.WGS-BWA-Tumor.json (100%)
[WORKER] ubuntu@i-ade4927f:/datastore/oozie-380fadbf-87a4-46b3-8ddb-6df03b55ed12/generated-scripts$ cat s28_git_manage_queued-jobs_downloading-jobs_3.stderr
Already on 'master'
To git@github.com:ICGC-TCGA-PanCancer/s3-transfer-operations.git
   dd509e6..221b2ab  master -> master
[WORKER] ubuntu@i-ade4927f:/datastore/oozie-380fadbf-87a4-46b3-8ddb-6df03b55ed12/generated-scripts$ cat s28_git_manage_queued-jobs_downloading-jobs_3.o844243305
Already on 'master'
To git@github.com:ICGC-TCGA-PanCancer/s3-transfer-operations.git
   dd509e6..221b2ab  master -> master
[WORKER] ubuntu@i-ade4927f:/datastore/oozie-380fadbf-87a4-46b3-8ddb-6df03b55ed12/generated-scripts$ cat s28_git_manage_queued-jobs_downloading-jobs_3.e844243305
Command run: 
bash -lc /datastore/oozie-380fadbf-87a4-46b3-8ddb-6df03b55ed12/generated-scripts/s28_git_manage_queued-jobs_downloading-jobs_3.sh 
Command exit code: 0
Your branch and 'origin/master' have diverged,
and have 1 and 1 different commit each, respectively.
HEAD is now at dd509e6 downloading-jobs: 9a442aa9-3cf4-405a-a7dd-dba6a0d92704.BOCA-UK.CGP_donor_1691214.CGP_specimen_1770699.WGS-BWA-Tumor.json
Fetching origin
[master 221b2ab] downloading-jobs: 96e252b8-911a-44c7-abc6-b924845e0be6.BOCA-UK.CGP_donor_1437417.CGP_specimen_1491214.WGS-BWA-Tumor.json
 1 file changed, 0 insertions(+), 0 deletions(-)
 rename s3-transfer-jobs/{queued-jobs => downloading-jobs}/96e252b8-911a-44c7-abc6-b924845e0be6.BOCA-UK.CGP_donor_1437417.CGP_specimen_1491214.WGS-BWA-Tumor.json (100%)
```

**Comment by junjun-zhang** [comment]
Moving a JSON  file in local git repo and push up to GitHub involves the following six git commands:

```
git checkout master && \
git reset --hard origin/master && \
git pull && \
git mv .... && \
git commit -m 'step name: json_file_name' && \
git push
```

The first three commands are to ensure local git is completely in-sync with the master branch on GitHub; the last three are the actual move and push back to GitHub. All commands are to be considered as part of a single transactional operation. Only when all commands succeeded, the transaction is successfully.

When multiple clients (worker nodes) perform the above operations on different JSON files, there will not be any conflict if each client performs the whole set of operations _sequentially_. This should be a typical scenario when the repo is small, not much commit history, not many clients, however, when repo size / commit history / number of clients increase, the chance of overlap between clients increase and may result in git conflict.

The quick fail feature is actually a very good thing when conflict happens, in distributed / concurrent execution environment. Measures should take to deal with conflict / race condition. What crucially  important is to protect system integrity no matter what happens.

There are easy things we can do to greatly mitigate the situation:
- avoid triggering the git operation on multiple clients in a very short period of time, instead, assign each client a random wait time, say in a range of 1 - 120 seconds. This is only applicable to workflow launch time
- re-try after some random wait time when previous operation failed

For the first point, I am not able to comment on how this could be implemented, as I am not aware of any details regarding how the workflow on each worker node is launched.

For the second point, we could have the JSON file move operation done using an external script instead of multiple chained bash commands. This will give us a lot flexibility, such script may then deal with conflict and re-try (with random wait time) by itself automatically when failure detected (instead of re-trying at the workflow level which may require manual work). The idea is similar to the wrapper script for gtdownload.

**Comment by niall-byrne** [comment]
I think we could implement this cleaner:

I was doing some testing last night, and I think to avoid local merge conflicts we want to complete the following steps:

1) git reset --hard origin/master
2) git pull

The idea being to clear out all staged changes locally with the git reset, and then you should be able to idempotently pull against the repo without causing merge conflicts.

I have tested this quite a bit and am satisfied this approach will solve this issue.

**Comment by junjun-zhang** [comment]
Yes, it should be `git pull` not just `git fetch`

**Comment by junjun-zhang** [comment]
Should this be closed? Niall?

**Comment by niall-byrne** [comment]
https://github.com/ICGC-TCGA-PanCancer/store-and-forward-workflow/commit/b79f1aaf100226020ae868ae143b289d9b78fc39
